

# This file was *autogenerated* from the file ./script.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2)#!/usr/bin/env sage

import sys



p = conway_polynomial(sys.argv[_sage_const_1 ], sys.argv[_sage_const_2 ]) # Например, для GF(3) и n = 1

with open("conway_poly.txt", "w") as file:
    file.write(str(p))

